### ISSUE TITLE
File missing 

### ISSUE THREAD

**Issue by thapakazi** [haude/osm2threejs#1]
could you please push python and shell scripts... @oozzal @rhoit @krazedkrish @rupakraj 
whoever of you have it... please push it...  :bow: 

Meanwhile: in my machine, when I was searching bhaisepati map...

```
sh: ~/osm2world/osm2world.sh: No such file or directory
python: can't open file '~/mrdoob/convert_obj_three.py': [Errno 2] No such file or directory
Errno::ENOENT - No such file or directory - temp/bhaisepati.obj:
    ~/Downloads/osm2threejs/lib/util.rb:69:in `read'
    ~/Downloads/osm2threejs/lib/util.rb:69:in `generate_json_data'
    ~/Downloads/osm2threejs/lib/util.rb:26:in `run_scripts'
    ~/Downloads/osm2threejs/lib/util.rb:19:in `get_map_from_location'
```

**Comment by thapakazi** [comment]
that gist is long dead @rhoit, can you dig and find whatever possible...

**Comment by rhoit** [comment]
my hdd crashed! no data!
